// <auto-generated />
using System;
using CareConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220074106_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareConnect.Core.Entities.Drug", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultDosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultDosage = "500mg",
                            DefaultFrequency = "1-0-1",
                            Name = "Paracetamol 500mg"
                        },
                        new
                        {
                            Id = 2,
                            DefaultDosage = "500mg",
                            DefaultFrequency = "1-0-1",
                            Name = "Amoxicillin 500mg"
                        },
                        new
                        {
                            Id = 3,
                            DefaultDosage = "400mg",
                            DefaultFrequency = "1-0-1",
                            Name = "Ibuprofen 400mg"
                        },
                        new
                        {
                            Id = 4,
                            DefaultDosage = "10mg",
                            DefaultFrequency = "0-0-1",
                            Name = "Cetirizine 10mg"
                        },
                        new
                        {
                            Id = 5,
                            DefaultDosage = "40mg",
                            DefaultFrequency = "1-0-0",
                            Name = "Pantoprazole 40mg"
                        },
                        new
                        {
                            Id = 6,
                            DefaultDosage = "500mg",
                            DefaultFrequency = "1-0-0",
                            Name = "Azithromycin 500mg"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.ICD11Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ICD11Codes");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int");

                    b.HasKey("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            Dosage = "500mg",
                            Duration = "3 Days",
                            Frequency = "1-0-1 (After food)",
                            Name = "Paracetamol",
                            PrescriptionId = 1
                        },
                        new
                        {
                            MedicineId = 2,
                            Dosage = "100mg",
                            Duration = "5 Days",
                            Frequency = "0-1-0 (After food)",
                            Name = "Vitamin C",
                            PrescriptionId = 1
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVyasa")
                        .HasColumnType("bit");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "",
                            BloodGroup = "O+",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            IsVyasa = false,
                            PatientFirstName = "John",
                            PatientLastName = "Doe",
                            PhoneNumber = "1234567890",
                            Prescription = ""
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            CreatedAt = new DateTime(2026, 2, 20, 7, 11, 6, 319, DateTimeKind.Utc).AddTicks(2680),
                            IsDispensed = false,
                            IsSigned = true,
                            Notes = "Take rest and drink water.",
                            VisitId = 2
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.TechTalkRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("College")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PptFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PptOriginalName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PptTopic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferredBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearOfStudy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("TechTalkRegistrations");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.TechTalkSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastExtendedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastExtensionAmount")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TechTalkSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsOpen = true,
                            LastExtensionAmount = 0,
                            MaxCapacity = 50
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("Advice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsultantDoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            Advice = "",
                            Complaints = "[]",
                            ConsultantDoctorName = "Dr. Smith",
                            CreatedAt = new DateTime(2026, 2, 20, 7, 41, 6, 319, DateTimeKind.Utc).AddTicks(2640),
                            Diagnosis = "[]",
                            PatientId = 1,
                            Priority = "Normal",
                            Status = "Vitals Recorded",
                            Tests = "[]"
                        },
                        new
                        {
                            VisitId = 2,
                            Advice = "",
                            Complaints = "[]",
                            ConsultantDoctorName = "Dr. Smith",
                            CreatedAt = new DateTime(2026, 2, 20, 6, 41, 6, 319, DateTimeKind.Utc).AddTicks(2640),
                            Diagnosis = "[]",
                            PatientId = 1,
                            Priority = "Normal",
                            Status = "Completed",
                            Tests = "[]"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Vitals", b =>
                {
                    b.Property<int>("VitalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VitalsId"));

                    b.Property<string>("BMI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pulse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpO2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VitalsId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Vitals");

                    b.HasData(
                        new
                        {
                            VitalsId = 1,
                            BMI = "",
                            BloodPressure = "120/80",
                            Height = "",
                            Pulse = "72",
                            SpO2 = "98",
                            Temperature = "98.6",
                            VisitId = 1,
                            Weight = "70"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Medicine", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Prescription", "Prescription")
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Visit", "Visit")
                        .WithOne("Prescription")
                        .HasForeignKey("CareConnect.Core.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Vitals", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Visit", "Visit")
                        .WithOne("Vitals")
                        .HasForeignKey("CareConnect.Core.Entities.Vitals", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.Navigation("Prescription");

                    b.Navigation("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
