// <auto-generated />
using System;
using CareConnect.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CareConnect.Core.Entities.ICD11Code", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ICD11Codes");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new
                        {
                            MedicineId = 1,
                            Dosage = "500mg",
                            Duration = "3 Days",
                            Frequency = "1-0-1 (After food)",
                            Name = "Paracetamol",
                            PrescriptionId = 1
                        },
                        new
                        {
                            MedicineId = 2,
                            Dosage = "100mg",
                            Duration = "5 Days",
                            Frequency = "0-1-0 (After food)",
                            Name = "Vitamin C",
                            PrescriptionId = 1
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVyasa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Address = "",
                            BloodGroup = "O+",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            IsVyasa = false,
                            PatientFirstName = "John",
                            PatientLastName = "Doe",
                            PhoneNumber = "1234567890",
                            Prescription = ""
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDispensed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            CreatedAt = new DateTime(2026, 2, 10, 12, 32, 58, 358, DateTimeKind.Utc).AddTicks(3450),
                            IsDispensed = false,
                            IsSigned = true,
                            Notes = "Take rest and drink water.",
                            VisitId = 2
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Credentials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Credentials = "RN",
                            Email = "nurse@hospital.com",
                            Name = "Nurse Joy",
                            PasswordHash = "$2a$11$dcbh.BB2pIEKXPNX2qdU6u17TFgnsFg4ZLdi3FhGT5mk3cY4cqNW.",
                            Role = "Nurse"
                        },
                        new
                        {
                            Id = 3,
                            Credentials = "B.Pharm",
                            Email = "pharmacist@hospital.com",
                            Name = "Pharma Bob",
                            PasswordHash = "$2a$11$dcbh.BB2pIEKXPNX2qdU6u17TFgnsFg4ZLdi3FhGT5mk3cY4cqNW.",
                            Role = "Pharmacist"
                        },
                        new
                        {
                            Id = 4,
                            Credentials = "Psychiatrist MBBS, D.P.M (Osm)",
                            Email = "vasista@careconnect.com",
                            Name = "Dr. BSG VASISTA",
                            PasswordHash = "$2a$11$gdCr.jAXM2JaZa/nuRXclOMnMTsbkkA/G2CLZboN.JmADqVMLhffC",
                            Role = "Doctor"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConsultantDoctorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VisitId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");

                    b.HasData(
                        new
                        {
                            VisitId = 1,
                            ConsultantDoctorName = "Dr. Smith",
                            CreatedAt = new DateTime(2026, 2, 10, 13, 2, 58, 358, DateTimeKind.Utc).AddTicks(3420),
                            PatientId = 1,
                            Priority = "Normal",
                            Status = "Vitals Recorded"
                        },
                        new
                        {
                            VisitId = 2,
                            ConsultantDoctorName = "Dr. Smith",
                            CreatedAt = new DateTime(2026, 2, 10, 12, 2, 58, 358, DateTimeKind.Utc).AddTicks(3420),
                            PatientId = 1,
                            Priority = "Normal",
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Vitals", b =>
                {
                    b.Property<int>("VitalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pulse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpO2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VisitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VitalsId");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Vitals");

                    b.HasData(
                        new
                        {
                            VitalsId = 1,
                            BloodPressure = "120/80",
                            Pulse = "72",
                            SpO2 = "98",
                            Temperature = "98.6",
                            VisitId = 1,
                            Weight = "70"
                        });
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Medicine", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Prescription", "Prescription")
                        .WithMany("Medicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Visit", "Visit")
                        .WithOne("Prescription")
                        .HasForeignKey("CareConnect.Core.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Vitals", b =>
                {
                    b.HasOne("CareConnect.Core.Entities.Visit", "Visit")
                        .WithOne("Vitals")
                        .HasForeignKey("CareConnect.Core.Entities.Vitals", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Patient", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Prescription", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("CareConnect.Core.Entities.Visit", b =>
                {
                    b.Navigation("Prescription");

                    b.Navigation("Vitals");
                });
#pragma warning restore 612, 618
        }
    }
}
